FROM alpine:3.22.1 AS disk

RUN apk add --no-cache curl

RUN set -eux; \
    case "$(uname -m)" in \
        'x86_64') \
            curl -sLo /disk https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img; \
            ;; \
        'aarch64') \
            curl -sLo /disk https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img; \
            ;; \
        *) echo >&2 "error: unsupported architecture '$(uname -m)'"; exit 1 ;; \
    esac

FROM scratch

COPY --from=disk /disk /disk
